### ISSUE TITLE
Develop a ListView that can store a items both on the screen and the Firestore database

### ISSUE THREAD

**Issue by JJalswo** [CMPUT301F23T29/agile-beast#26]
#4

**Comment by peanutChowder** [comment]
Creating the firebase db and connecting it to code, as well as creating a way to display items (i.e. ListAdapter, ListView)

**Comment by peanutChowder** [comment]
Still need to add label and photo support in firebase db

**Comment by JJalswo** [comment]
Photo is implemented closing the issues
